export const environment = {
  production: false,
  apiUrl: 'http://localhost:1200',
  getalumnosEndpoint: '/api/applicants',
  loginEndpoint: '/auth/login',
  getresultadosEndpoint: '/api/admin/results',
  getresultmostrarEndpoint: '/api/applicant/me',
  postsecretariasEndpoint: '/auth/users',
  fichasdispiniblesEndpoint: '/admin/vacancies',
  cambiodecarreraEndpoint: '/api/applicant',
  respuestasolicitudEndpoint: '/api/applicant/change-career/requests',
  accessRestrictionEndpoint: '/api/admin/access-restriction',
  getApplicantbyid: '/api/admin/applicants',
  getUsuariosEndpoint:'/api/admin/users',
};